apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aa697ui7v-java-springboot
  janus-idp.io/tekton: aa697ui7v-java-springboot
  backstage.io/kubernetes-id: aa697ui7v-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aa697ui7v-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
